# Generated by Django 2.1.3 on 2018-11-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_selling',
            name='Seller',
        ),
    ]
