# Generated by Django 2.1.3 on 2018-11-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0004_category_products_selling'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_Buying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now=True)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile')),
                ('Products_Selling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Products_Selling')),
            ],
        ),
    ]
